---

firewalld:
  actived: false
  enabled_ports:
    - 9092
    - 2181
    - 2888
    - 3888

java_home: "/usr/lib/jvm/jdk1.8.0_102"

install_offline: true
auto_numbering: false
# auto_numbering will generating zk's id and kafka's broker_id
# by using inventory_hostname's naming rule: "sometime-number", eg:
# [kafka]
# kafka-1  => id=1
# kafka-2  => id=2
# kafka-3  => id=3
