---
zk_hosts:
  - host: zk-1
    id: 1
  - host2:
    host: zk-2
    id: 2
  - host3:
    host: zk-3
    id: 3

# zk_parent_dir:
# data_dir:
# data_log_dir:
# zk_client_port:
zk_register_path_env: true
zk_env:
  JAVA_OPTS: '"-Xmx512M -Xms512M"'
  JAVA_HOME: "{{ java_home }}"

