---
- name: Configure zookeeper-env.sh
  template: src=zookeeper-env.sh.j2 dest={{ zk_dir }}/conf/zookeeper-env.sh owner=zookeeper group=zookeeper
  tags: deploy
  notify:
    - Restart zookeeper
  when: zk_env is defined and zk_env|length > 0


- name: Update the log4j config
  template: src=log4j.properties.j2 dest={{ zk_dir }}/conf/log4j.properties
  tags: deploy
  notify:
    - Restart zookeeper


- name: Enable zookeeper Service
  service: name=zookeeper enabled=true use=systemd
  tags:
    - service


