---
- name: Systemd script
  template: src=kafka.service.j2 dest=/lib/systemd/system/kafka.service
  when: ansible_service_mgr == 'systemd'
  notify:
    - Reload systemctl daemon


- name: force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers
